# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Social Board' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Social Board
  pod 'AlamofireImage'


  target 'Social BoardTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Social BoardUITests' do
    # Pods for testing
  end

end
